<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
	<PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <RunCodeAnalysis>false</RunCodeAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NetMQ" Version="4.0.1.13" />
  </ItemGroup>
  <ItemGroup>
	  <ProjectReference Include="..\LegacyWrapper.Common\LegacyWrapper.Common.csproj">
		  <AdditionalProperties>TargetFramework=net8.0</AdditionalProperties>
		  <ExcludeAssets>netstandard2.0</ExcludeAssets>
	  </ProjectReference>
  </ItemGroup>

</Project>